### ISSUE TITLE
Exception: function `get_current_opengl_sharegroup` returned NULL. Did you create an openGL context yet?

### ISSUE THREAD

**Issue by ubernaut** [srossross/oclpb#2]
python setup.py build

sudo python setup.py install 

These examples work fine: add_vectors.py, and  print_device_info.py

But  gl_interop_demo.py  fails with the following error:

cos@cos-laptop:~/oclpb/examples$ python gl_interop_demo.py 
Traceback (most recent call last):
  File "gl_interop_demo.py", line 90, in <module>
    main()
  File "gl_interop_demo.py", line 86, in main
    initialize()
  File "gl_interop_demo.py", line 35, in initialize
    ctx = cl.gl.context()
  File "clgl.pyx", line 394, in opencl.clgl.context (opencl/clgl.c:4628)
  File "clgl.pyx", line 107, in opencl.clgl.set_opengl_properties (opencl/clgl.c:1460)
Exception: function `get_current_opengl_sharegroup` returned NULL. Did you create an openGL context yet?

I'm running xubuntu 11.10 with the nvidia 295.40 driver. the video card is a Quadro NVS 160.

The pyglet/pyopengl pyopencl interop stuff is working for me still do you think they may be conflicting with your stuff?   

 I will also post this to your github issues page in case if anyone else runs into it.

Thanks a million for your time. I'll also try this on my desktop at home with a gtx260. 

-Collin

**Comment by srossross** [comment]
@ubernaut this is an incredibly simple fix, but I haven't had access to a non-mac machine in a while. 

If you are familiar with OpenCL, take a look in `opencl.clgl.set_opengl_properties` and add system specific statement there.

I'll probably get to this in less than a week.
